language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo pip install cpp-coveralls

before_script:
  - autoreconf -iv
  - ./configure

script:
  - make
  - make check

after_success:
  - make clean
  - make json_unit CXXFLAGS="-fprofile-arcs -ftest-coverage"
  - ./json_unit
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
